name: Deploy to Server

on:
  push:
    branches:
      - main  # Change to your branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@209.38.123.141 "
            cd \wsl.localhost\Ubuntu-24.04\home\lemon\projects\dockerized-node-service &&
            git pull origin main &&
            docker compose down &&
            docker compose up -d --build
          "
