global:
  scrape_interval: 15s
  evaluation_interval: 30s
  scrape_timeout: 10s

rule_files:
  - /etc/prometheus/alerting_rules.yml
  - /etc/prometheus/recording_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']
